/**
 * Message codes for VSCode extension UI messages and structured logging.
 * Extension-only i18n system - core layer stays English for technical messages.
 *
 * Values match keys for clarity in logs and i18n mapping.
 *
 * Architecture: Following Option D (Extension-Only i18n) where:
 * - Core layer: Hardcoded English (industry standard for technical messages)
 * - Extension layer: Localized UI messages (this file)
 */
export enum MessageCode {
  // Keep the keys in alphabetical order.

  ALREADY_BOUND_TO_DESTINATION = 'ALREADY_BOUND_TO_DESTINATION',
  BOUND_EDITOR_CLOSED_AUTO_UNBOUND = 'BOUND_EDITOR_CLOSED_AUTO_UNBOUND',

  // Configuration messages (used in logging)
  CONFIG_LOADED = 'CONFIG_LOADED',
  CONFIG_USING_DEFAULTS = 'CONFIG_USING_DEFAULTS',

  // Error messages (user-facing UI)
  ERROR_CLAUDE_CODE_NOT_AVAILABLE = 'ERROR_CLAUDE_CODE_NOT_AVAILABLE',
  ERROR_CURSOR_AI_NOT_AVAILABLE = 'ERROR_CURSOR_AI_NOT_AVAILABLE',
  ERROR_GITHUB_COPILOT_CHAT_NOT_AVAILABLE = 'ERROR_GITHUB_COPILOT_CHAT_NOT_AVAILABLE',
  ERROR_NAVIGATION_FAILED = 'ERROR_NAVIGATION_FAILED',
  ERROR_NO_ACTIVE_TERMINAL = 'ERROR_NO_ACTIVE_TERMINAL',
  ERROR_NO_ACTIVE_TEXT_EDITOR = 'ERROR_NO_ACTIVE_TEXT_EDITOR',
  ERROR_TEXT_EDITOR_NOT_TEXT_LIKE = 'ERROR_TEXT_EDITOR_NOT_TEXT_LIKE',
  ERROR_TEXT_EDITOR_REQUIRES_SPLIT = 'ERROR_TEXT_EDITOR_REQUIRES_SPLIT',

  // Information messages (user-facing UI)
  INFO_CLAUDE_CODE_NOT_AVAILABLE = 'INFO_CLAUDE_CODE_NOT_AVAILABLE',
  INFO_CLAUDE_CODE_USER_INSTRUCTIONS = 'INFO_CLAUDE_CODE_USER_INSTRUCTIONS',
  INFO_COMMIT_HASH_COPIED = 'INFO_COMMIT_HASH_COPIED',
  INFO_CURSOR_AI_NOT_AVAILABLE = 'INFO_CURSOR_AI_NOT_AVAILABLE',
  INFO_CURSOR_AI_USER_INSTRUCTIONS = 'INFO_CURSOR_AI_USER_INSTRUCTIONS',
  INFO_GITHUB_COPILOT_CHAT_NOT_AVAILABLE = 'INFO_GITHUB_COPILOT_CHAT_NOT_AVAILABLE',
  INFO_GITHUB_COPILOT_CHAT_USER_INSTRUCTIONS = 'INFO_GITHUB_COPILOT_CHAT_USER_INSTRUCTIONS',
  INFO_JUMP_FOCUS_FAILED = 'INFO_JUMP_FOCUS_FAILED',
  INFO_JUMP_NO_DESTINATION_BOUND = 'INFO_JUMP_NO_DESTINATION_BOUND',
  INFO_NAVIGATION_SUCCESS = 'INFO_NAVIGATION_SUCCESS',

  // Smart bind confirmation dialog (user-facing UI)
  SMART_BIND_CONFIRM_NO_DESCRIPTION = 'SMART_BIND_CONFIRM_NO_DESCRIPTION',
  SMART_BIND_CONFIRM_NO_KEEP = 'SMART_BIND_CONFIRM_NO_KEEP',
  SMART_BIND_CONFIRM_PLACEHOLDER = 'SMART_BIND_CONFIRM_PLACEHOLDER',
  SMART_BIND_CONFIRM_YES_DESCRIPTION = 'SMART_BIND_CONFIRM_YES_DESCRIPTION',
  SMART_BIND_CONFIRM_YES_REPLACE = 'SMART_BIND_CONFIRM_YES_REPLACE',

  // Status bar messages (user-facing UI)
  STATUS_BAR_DESTINATION_BINDING_REMOVED_TERMINAL_CLOSED = 'STATUS_BAR_DESTINATION_BINDING_REMOVED_TERMINAL_CLOSED',
  STATUS_BAR_DESTINATION_BOUND = 'STATUS_BAR_DESTINATION_BOUND',
  STATUS_BAR_DESTINATION_NOT_BOUND = 'STATUS_BAR_DESTINATION_NOT_BOUND',
  STATUS_BAR_DESTINATION_REBOUND = 'STATUS_BAR_DESTINATION_REBOUND',
  STATUS_BAR_DESTINATION_UNBOUND = 'STATUS_BAR_DESTINATION_UNBOUND',
  STATUS_BAR_ITEM_TEXT = 'STATUS_BAR_ITEM_TEXT',
  STATUS_BAR_JUMP_SUCCESS_CLAUDE_CODE = 'STATUS_BAR_JUMP_SUCCESS_CLAUDE_CODE',
  STATUS_BAR_JUMP_SUCCESS_CURSOR_AI = 'STATUS_BAR_JUMP_SUCCESS_CURSOR_AI',
  STATUS_BAR_JUMP_SUCCESS_EDITOR = 'STATUS_BAR_JUMP_SUCCESS_EDITOR',
  STATUS_BAR_JUMP_SUCCESS_GITHUB_COPILOT_CHAT = 'STATUS_BAR_JUMP_SUCCESS_GITHUB_COPILOT_CHAT',
  STATUS_BAR_JUMP_SUCCESS_TERMINAL = 'STATUS_BAR_JUMP_SUCCESS_TERMINAL',
  STATUS_BAR_LINK_COPIED_TO_CLIPBOARD = 'STATUS_BAR_LINK_COPIED_TO_CLIPBOARD',
  STATUS_BAR_MENU_BOOKMARKS_ADD_CURRENT = 'STATUS_BAR_MENU_BOOKMARKS_ADD_CURRENT',
  STATUS_BAR_MENU_BOOKMARKS_EMPTY = 'STATUS_BAR_MENU_BOOKMARKS_EMPTY',
  STATUS_BAR_MENU_BOOKMARKS_MANAGE = 'STATUS_BAR_MENU_BOOKMARKS_MANAGE',
  STATUS_BAR_MENU_BOOKMARKS_SECTION_LABEL = 'STATUS_BAR_MENU_BOOKMARKS_SECTION_LABEL',
  STATUS_BAR_MENU_ITEM_JUMP_DISABLED_DESC = 'STATUS_BAR_MENU_ITEM_JUMP_DISABLED_DESC',
  STATUS_BAR_MENU_ITEM_JUMP_DISABLED_LABEL = 'STATUS_BAR_MENU_ITEM_JUMP_DISABLED_LABEL',
  STATUS_BAR_MENU_ITEM_JUMP_ENABLED_LABEL = 'STATUS_BAR_MENU_ITEM_JUMP_ENABLED_LABEL',
  STATUS_BAR_MENU_ITEM_VERSION_INFO_LABEL = 'STATUS_BAR_MENU_ITEM_VERSION_INFO_LABEL',
  STATUS_BAR_MENU_PLACEHOLDER = 'STATUS_BAR_MENU_PLACEHOLDER',
  STATUS_BAR_MENU_TITLE = 'STATUS_BAR_MENU_TITLE',
  STATUS_BAR_MENU_TOOLTIP = 'STATUS_BAR_MENU_TOOLTIP',

  // Warning messages (user-facing UI)
  WARN_NAVIGATION_FILE_NOT_FOUND = 'WARN_NAVIGATION_FILE_NOT_FOUND',
  WARN_NAVIGATION_UNTITLED_FILE = 'WARN_NAVIGATION_UNTITLED_FILE',

  // Keep the keys in alphabetical order.
}
