/**
 * Message codes for VSCode extension UI messages and structured logging.
 * Extension-only i18n system - core layer stays English for technical messages.
 *
 * Values match keys for clarity in logs and i18n mapping.
 *
 * Architecture: Following Option D (Extension-Only i18n) where:
 * - Core layer: Hardcoded English (industry standard for technical messages)
 * - Extension layer: Localized UI messages (this file)
 */
export enum MessageCode {
  // Keep the keys in alphabetical order.

  ALREADY_BOUND_TO_DESTINATION = 'ALREADY_BOUND_TO_DESTINATION',
  BOOKMARK_ACTION_ADD = 'BOOKMARK_ACTION_ADD',
  BOOKMARK_ACTION_MANAGE = 'BOOKMARK_ACTION_MANAGE',
  BOOKMARK_ADD_INPUT_PLACEHOLDER = 'BOOKMARK_ADD_INPUT_PLACEHOLDER',
  BOOKMARK_ADD_INPUT_PROMPT = 'BOOKMARK_ADD_INPUT_PROMPT',
  BOOKMARK_LIST_EMPTY = 'BOOKMARK_LIST_EMPTY',
  BOOKMARK_LIST_PLACEHOLDER = 'BOOKMARK_LIST_PLACEHOLDER',
  BOOKMARK_LIST_TITLE = 'BOOKMARK_LIST_TITLE',
  BOOKMARK_MANAGE_CONFIRM_DELETE = 'BOOKMARK_MANAGE_CONFIRM_DELETE',
  BOOKMARK_MANAGE_CONFIRM_DELETE_CANCEL = 'BOOKMARK_MANAGE_CONFIRM_DELETE_CANCEL',
  BOOKMARK_MANAGE_CONFIRM_DELETE_YES = 'BOOKMARK_MANAGE_CONFIRM_DELETE_YES',
  BOOKMARK_MANAGE_DELETED = 'BOOKMARK_MANAGE_DELETED',
  BOOKMARK_MANAGE_EMPTY = 'BOOKMARK_MANAGE_EMPTY',
  BOOKMARK_MANAGE_ERROR_DELETE_FAILED = 'BOOKMARK_MANAGE_ERROR_DELETE_FAILED',
  BOOKMARK_MANAGE_PLACEHOLDER = 'BOOKMARK_MANAGE_PLACEHOLDER',
  BOOKMARK_MANAGE_TITLE = 'BOOKMARK_MANAGE_TITLE',
  BOUND_EDITOR_CLOSED_AUTO_UNBOUND = 'BOUND_EDITOR_CLOSED_AUTO_UNBOUND',

  // Configuration messages (used in logging)
  CONFIG_LOADED = 'CONFIG_LOADED',
  CONFIG_USING_DEFAULTS = 'CONFIG_USING_DEFAULTS',

  // Content names (user-facing, used in status bar messages)
  CONTENT_NAME_FILE_PATH = 'CONTENT_NAME_FILE_PATH',
  CONTENT_NAME_PORTABLE_RANGELINK = 'CONTENT_NAME_PORTABLE_RANGELINK',
  CONTENT_NAME_RANGELINK = 'CONTENT_NAME_RANGELINK',
  CONTENT_NAME_SELECTED_TEXT = 'CONTENT_NAME_SELECTED_TEXT',

  // Destination display formats (user-facing, used in picker menus)
  DESTINATION_TERMINAL_DISPLAY_FORMAT = 'DESTINATION_TERMINAL_DISPLAY_FORMAT',

  // Error messages (user-facing UI)
  ERROR_BOOKMARK_EMPTY_LABEL = 'ERROR_BOOKMARK_EMPTY_LABEL',
  ERROR_BOOKMARK_LINK_GENERATION_FAILED = 'ERROR_BOOKMARK_LINK_GENERATION_FAILED',
  ERROR_BOOKMARK_NO_ACTIVE_EDITOR = 'ERROR_BOOKMARK_NO_ACTIVE_EDITOR',
  ERROR_BOOKMARK_SAVE_FAILED = 'ERROR_BOOKMARK_SAVE_FAILED',
  ERROR_BOOKMARK_UNTITLED_FILE = 'ERROR_BOOKMARK_UNTITLED_FILE',
  ERROR_CLAUDE_CODE_NOT_AVAILABLE = 'ERROR_CLAUDE_CODE_NOT_AVAILABLE',
  ERROR_CURSOR_AI_NOT_AVAILABLE = 'ERROR_CURSOR_AI_NOT_AVAILABLE',
  ERROR_GITHUB_COPILOT_CHAT_NOT_AVAILABLE = 'ERROR_GITHUB_COPILOT_CHAT_NOT_AVAILABLE',
  ERROR_INVALID_DELIMITER_CONFIG = 'ERROR_INVALID_DELIMITER_CONFIG',
  ERROR_LINK_GENERATION_FAILED = 'ERROR_LINK_GENERATION_FAILED',
  ERROR_NAVIGATION_FAILED = 'ERROR_NAVIGATION_FAILED',
  ERROR_NO_ACTIVE_EDITOR = 'ERROR_NO_ACTIVE_EDITOR',
  ERROR_NO_ACTIVE_TERMINAL = 'ERROR_NO_ACTIVE_TERMINAL',
  ERROR_NO_ACTIVE_TEXT_EDITOR = 'ERROR_NO_ACTIVE_TEXT_EDITOR',
  ERROR_NO_TEXT_SELECTED = 'ERROR_NO_TEXT_SELECTED',
  ERROR_PASTE_FILE_PATH_NO_ACTIVE_FILE = 'ERROR_PASTE_FILE_PATH_NO_ACTIVE_FILE',
  ERROR_TERMINAL_LINK_INVALID_FORMAT = 'ERROR_TERMINAL_LINK_INVALID_FORMAT',
  ERROR_TEXT_EDITOR_BINARY_FILE = 'ERROR_TEXT_EDITOR_BINARY_FILE',
  ERROR_TEXT_EDITOR_READ_ONLY = 'ERROR_TEXT_EDITOR_READ_ONLY',
  ERROR_VERSION_INFO_NOT_AVAILABLE = 'ERROR_VERSION_INFO_NOT_AVAILABLE',

  // Information messages (user-facing UI)
  INFO_CLAUDE_CODE_NOT_AVAILABLE = 'INFO_CLAUDE_CODE_NOT_AVAILABLE',
  INFO_CLAUDE_CODE_USER_INSTRUCTIONS = 'INFO_CLAUDE_CODE_USER_INSTRUCTIONS',
  INFO_COMMIT_HASH_COPIED = 'INFO_COMMIT_HASH_COPIED',
  INFO_CURSOR_AI_NOT_AVAILABLE = 'INFO_CURSOR_AI_NOT_AVAILABLE',
  INFO_CURSOR_AI_USER_INSTRUCTIONS = 'INFO_CURSOR_AI_USER_INSTRUCTIONS',
  INFO_GITHUB_COPILOT_CHAT_NOT_AVAILABLE = 'INFO_GITHUB_COPILOT_CHAT_NOT_AVAILABLE',
  INFO_GITHUB_COPILOT_CHAT_USER_INSTRUCTIONS = 'INFO_GITHUB_COPILOT_CHAT_USER_INSTRUCTIONS',
  INFO_JUMP_FOCUS_FAILED = 'INFO_JUMP_FOCUS_FAILED',
  INFO_JUMP_NO_DESTINATIONS_AVAILABLE = 'INFO_JUMP_NO_DESTINATIONS_AVAILABLE',
  INFO_JUMP_QUICK_PICK_PLACEHOLDER = 'INFO_JUMP_QUICK_PICK_PLACEHOLDER',
  INFO_NAVIGATION_EMPTY_INPUT = 'INFO_NAVIGATION_EMPTY_INPUT',
  INFO_NAVIGATION_INPUT_BOX_PLACEHOLDER = 'INFO_NAVIGATION_INPUT_BOX_PLACEHOLDER',
  INFO_NAVIGATION_INPUT_BOX_PROMPT = 'INFO_NAVIGATION_INPUT_BOX_PROMPT',
  INFO_NAVIGATION_INVALID_LINK = 'INFO_NAVIGATION_INVALID_LINK',
  INFO_NAVIGATION_SUCCESS = 'INFO_NAVIGATION_SUCCESS',
  INFO_PASTE_CONTENT_NO_DESTINATIONS_AVAILABLE = 'INFO_PASTE_CONTENT_NO_DESTINATIONS_AVAILABLE',
  INFO_PASTE_CONTENT_QUICK_PICK_DESTINATIONS_CHOOSE_BELOW = 'INFO_PASTE_CONTENT_QUICK_PICK_DESTINATIONS_CHOOSE_BELOW',
  INFO_SELF_PASTE_CONTENT_SKIPPED = 'INFO_SELF_PASTE_CONTENT_SKIPPED',
  INFO_SELF_PASTE_LINK_SKIPPED = 'INFO_SELF_PASTE_LINK_SKIPPED',
  INFO_VERSION_COPY_COMMIT_HASH_BUTTON = 'INFO_VERSION_COPY_COMMIT_HASH_BUTTON',
  INFO_VERSION_DIRTY_INDICATOR = 'INFO_VERSION_DIRTY_INDICATOR',
  INFO_VERSION_INFO = 'INFO_VERSION_INFO',

  // Smart bind confirmation dialog (user-facing UI)
  SMART_BIND_CONFIRM_NO_DESCRIPTION = 'SMART_BIND_CONFIRM_NO_DESCRIPTION',
  SMART_BIND_CONFIRM_NO_KEEP = 'SMART_BIND_CONFIRM_NO_KEEP',
  SMART_BIND_CONFIRM_PLACEHOLDER = 'SMART_BIND_CONFIRM_PLACEHOLDER',
  SMART_BIND_CONFIRM_YES_DESCRIPTION = 'SMART_BIND_CONFIRM_YES_DESCRIPTION',
  SMART_BIND_CONFIRM_YES_REPLACE = 'SMART_BIND_CONFIRM_YES_REPLACE',

  // Status bar messages (user-facing UI)
  STATUS_BAR_DESTINATION_BINDING_REMOVED_TERMINAL_CLOSED = 'STATUS_BAR_DESTINATION_BINDING_REMOVED_TERMINAL_CLOSED',
  STATUS_BAR_DESTINATION_BOUND = 'STATUS_BAR_DESTINATION_BOUND',
  STATUS_BAR_DESTINATION_NOT_BOUND = 'STATUS_BAR_DESTINATION_NOT_BOUND',
  STATUS_BAR_DESTINATION_REBOUND = 'STATUS_BAR_DESTINATION_REBOUND',
  STATUS_BAR_DESTINATION_UNBOUND = 'STATUS_BAR_DESTINATION_UNBOUND',
  STATUS_BAR_ITEM_TEXT = 'STATUS_BAR_ITEM_TEXT',
  STATUS_BAR_JUMP_SUCCESS_CLAUDE_CODE = 'STATUS_BAR_JUMP_SUCCESS_CLAUDE_CODE',
  STATUS_BAR_JUMP_SUCCESS_CURSOR_AI = 'STATUS_BAR_JUMP_SUCCESS_CURSOR_AI',
  STATUS_BAR_JUMP_SUCCESS_EDITOR = 'STATUS_BAR_JUMP_SUCCESS_EDITOR',
  STATUS_BAR_JUMP_SUCCESS_GITHUB_COPILOT_CHAT = 'STATUS_BAR_JUMP_SUCCESS_GITHUB_COPILOT_CHAT',
  STATUS_BAR_JUMP_SUCCESS_TERMINAL = 'STATUS_BAR_JUMP_SUCCESS_TERMINAL',
  STATUS_BAR_LINK_COPIED_TO_CLIPBOARD = 'STATUS_BAR_LINK_COPIED_TO_CLIPBOARD',
  STATUS_BAR_LINK_SENT_TO_DESTINATION = 'STATUS_BAR_LINK_SENT_TO_DESTINATION',
  STATUS_BAR_BOOKMARK_SAVED = 'STATUS_BAR_BOOKMARK_SAVED',
  STATUS_BAR_MENU_BOOKMARKS_SECTION_LABEL = 'STATUS_BAR_MENU_BOOKMARKS_SECTION_LABEL',
  STATUS_BAR_MENU_DESTINATIONS_CHOOSE_BELOW = 'STATUS_BAR_MENU_DESTINATIONS_CHOOSE_BELOW',
  STATUS_BAR_MENU_DESTINATIONS_NONE_AVAILABLE = 'STATUS_BAR_MENU_DESTINATIONS_NONE_AVAILABLE',
  STATUS_BAR_MENU_ITEM_JUMP_ENABLED_LABEL = 'STATUS_BAR_MENU_ITEM_JUMP_ENABLED_LABEL',
  STATUS_BAR_MENU_ITEM_NAVIGATE_TO_LINK_LABEL = 'STATUS_BAR_MENU_ITEM_NAVIGATE_TO_LINK_LABEL',
  STATUS_BAR_MENU_ITEM_VERSION_INFO_LABEL = 'STATUS_BAR_MENU_ITEM_VERSION_INFO_LABEL',
  STATUS_BAR_MENU_PLACEHOLDER = 'STATUS_BAR_MENU_PLACEHOLDER',
  STATUS_BAR_MENU_TITLE = 'STATUS_BAR_MENU_TITLE',
  STATUS_BAR_MENU_TOOLTIP = 'STATUS_BAR_MENU_TOOLTIP',

  // Terminal picker messages (user-facing UI)
  TERMINAL_PICKER_ACTIVE_DESCRIPTION = 'TERMINAL_PICKER_ACTIVE_DESCRIPTION',
  TERMINAL_PICKER_BIND_ONLY_PLACEHOLDER = 'TERMINAL_PICKER_BIND_ONLY_PLACEHOLDER',
  TERMINAL_PICKER_MORE_LABEL = 'TERMINAL_PICKER_MORE_LABEL',
  TERMINAL_PICKER_MORE_TERMINALS_DESCRIPTION = 'TERMINAL_PICKER_MORE_TERMINALS_DESCRIPTION',
  TERMINAL_PICKER_PLACEHOLDER = 'TERMINAL_PICKER_PLACEHOLDER',
  TERMINAL_PICKER_TERMINAL_LABEL_FORMAT = 'TERMINAL_PICKER_TERMINAL_LABEL_FORMAT',
  TERMINAL_PICKER_TITLE = 'TERMINAL_PICKER_TITLE',

  // Warning messages (user-facing UI)
  WARN_NAVIGATION_FILE_NOT_FOUND = 'WARN_NAVIGATION_FILE_NOT_FOUND',
  WARN_NAVIGATION_UNTITLED_FILE = 'WARN_NAVIGATION_UNTITLED_FILE',
  WARN_PASTE_FAILED_EDITOR_HIDDEN = 'WARN_PASTE_FAILED_EDITOR_HIDDEN',
  WARN_PASTE_FAILED_TERMINAL = 'WARN_PASTE_FAILED_TERMINAL',

  // Keep the keys in alphabetical order.
}
