name: 'Check Formatting and Linting'
description: 'Run format check, linting, and type checking'

inputs:
  skip-format:
    description: 'Skip format checking'
    required: false
    default: 'false'
  skip-lint:
    description: 'Skip linting'
    required: false
    default: 'false'
  skip-types:
    description: 'Skip type checking'
    required: false
    default: 'false'
  allow-format-failure:
    description: 'Allow format check to fail without blocking CI'
    required: false
    default: 'false'
  allow-lint-failure:
    description: 'Allow linting to fail without blocking CI'
    required: false
    default: 'false'
  allow-types-failure:
    description: 'Allow type checking to fail without blocking CI'
    required: false
    default: 'false'

runs:
  using: 'composite'
  steps:
    - name: Check formatting with Prettier
      if: inputs.skip-format != 'true'
      shell: bash
      run: |
        echo "Running format check..."
        if ! pnpm format; then
          if [ "${{ inputs.allow-format-failure }}" = "true" ]; then
            echo "::warning::Format check found issues (allowed to fail)"
          else
            exit 1
          fi
        fi

    - name: Run ESLint
      if: inputs.skip-lint != 'true'
      shell: bash
      run: |
        echo "Running linter..."
        if ! pnpm lint; then
          if [ "${{ inputs.allow-lint-failure }}" = "true" ]; then
            echo "::warning::Linting found issues (allowed to fail)"
          else
            exit 1
          fi
        fi

    - name: Type check with TypeScript
      if: inputs.skip-types != 'true'
      shell: bash
      run: |
        echo "Running type check..."
        if ! pnpm compile; then
          if [ "${{ inputs.allow-types-failure }}" = "true" ]; then
            echo "::warning::Type checking found issues (allowed to fail)"
          else
            exit 1
          fi
        fi
