export { DEFAULT_DELIMITERS } from './DEFAULT_DELIMITERS';
export { MAX_LINK_LENGTH } from './MAX_LINK_LENGTH';
export { PORTABLE_METADATA_SEPARATOR } from './PORTABLE_METADATA_SEPARATOR';
export { RESERVED_CHARS } from './RESERVED_CHARS';
