export { MAX_LINK_LENGTH } from './maxLinkLength';
export { TEXT_FRAGMENT_DIRECTIVE, TEXT_FRAGMENT_DIRECTIVE_PREFIX, TEXT_FRAGMENT_SEPARATOR } from './textFragment';
export { DEFAULT_CASE_SENSITIVITY, DEFAULT_COLLAPSE_WHITESPACE, DEFAULT_MAX_CANDIDATES } from './textMatch';
