export { Result } from './Result';
export { CoreResult } from './CoreResult';
export { Selection } from './Selection';
export { InputSelection } from './InputSelection';
export { DelimiterConfig, DelimiterConfigGetter } from './DelimiterConfig';
export { RangeFormat } from './RangeFormat';
export { PathFormat } from './PathFormat';
export { LinkType } from './LinkType';
export { SelectionCoverage } from './SelectionCoverage';
export { SelectionType } from './SelectionType';
export { RangeNotation } from './RangeNotation';
export { ComputedSelection } from './ComputedSelection';
export { FormatOptions } from './FormatOptions';
export { FormattedLink } from './FormattedLink';
export { EditorPosition } from './EditorPosition';
export { LinkPosition } from './LinkPosition';
export { ParsedLink } from './ParsedLink';
export { DetectedLink } from './DetectedLink';
