/**
 * Centralized message codes for all RangeLink messages
 * Organized by category (1xxx = Configuration, 2xxx = BYOD, etc.)
 * These codes enable future i18n support by decoupling message identification from formatting
 */
export enum RangeLinkMessageCode {
  // Configuration messages (1xxx)
  CONFIG_LOADED = 'MSG_1001',
  CONFIG_USING_DEFAULTS = 'MSG_1002',
  CONFIG_ERR_DELIMITER_INVALID = 'ERR_1001',
  CONFIG_ERR_DELIMITER_EMPTY = 'ERR_1002',
  CONFIG_ERR_DELIMITER_DIGITS = 'ERR_1003',
  CONFIG_ERR_DELIMITER_WHITESPACE = 'ERR_1004',
  CONFIG_ERR_DELIMITER_RESERVED = 'ERR_1005',
  CONFIG_ERR_DELIMITER_NOT_UNIQUE = 'ERR_1006',
  CONFIG_ERR_DELIMITER_SUBSTRING_CONFLICT = 'ERR_1007',
  CONFIG_ERR_HASH_NOT_SINGLE_CHAR = 'ERR_1008',
  CONFIG_ERR_UNKNOWN = 'ERR_1099',

  // BYOD parsing messages (2xxx)
  BYOD_ERR_INVALID_FORMAT = 'ERR_2001',
  BYOD_ERR_HASH_INVALID = 'ERR_2002',
  BYOD_ERR_DELIMITER_VALIDATION = 'ERR_2003',
  BYOD_ERR_FORMAT_MISMATCH = 'ERR_2004',
  BYOD_ERR_POSITION_RECOVERY_FAILED = 'ERR_2005',
  BYOD_ERR_RECTANGULAR_MODE_DETECTION = 'ERR_2006',
  BYOD_WARN_POSITION_FROM_LOCAL = 'WARN_2001',
  BYOD_WARN_POSITION_FROM_DEFAULT = 'WARN_2002',
  BYOD_WARN_EXTRA_DELIMITER = 'WARN_2003',

  // Selection validation errors (3xxx)
  SELECTION_ERR_EMPTY = 'ERR_3001',
  SELECTION_ERR_NORMAL_MULTIPLE = 'ERR_3002',
  SELECTION_ERR_BACKWARD_LINE = 'ERR_3003',
  SELECTION_ERR_BACKWARD_CHARACTER = 'ERR_3004',
  SELECTION_ERR_NEGATIVE_COORDINATES = 'ERR_3005',
  SELECTION_ERR_RECTANGULAR_UNSORTED = 'ERR_3006',
  SELECTION_ERR_RECTANGULAR_MULTILINE = 'ERR_3007',
  SELECTION_ERR_RECTANGULAR_MISMATCHED_COLUMNS = 'ERR_3008',
  SELECTION_ERR_RECTANGULAR_NON_CONTIGUOUS = 'ERR_3009',
  SELECTION_ERR_UNKNOWN_TYPE = 'ERR_3010',
  SELECTION_ERR_ZERO_WIDTH = 'ERR_3011',
}
